# Guide for the New R Analysis Developer


## Install and Set up R and R Studio

R is the statistical programming language that R Studio understands. I think of R Studio as being the front-end user interface to the coding language R which is running in the background. For this all to work you you need to download two things to start; R and R Studio.

1) Watch my [Youtube Video](https://youtu.be/G3kaguwW8yc) on how to install R and R Studio
2) Go to https://cran.r-project.org/ and follow the link to the download for your operating system.
3) Go to https://www.rstudio.com/products/rstudio/download/ to download R studio

### Familiarize yourself with R and R-Studio

Now that you have downloaded the tools you need, lets get familiar first with R-Studio and then the R programming language.

### R Studio
Watch [this R-Studio Tutorial](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-part-1/) for a nice introduction to the software.

### R Programming Language

To begin getting familiar with the R programming language lets install your first package in R-Studio. You can think of packages as extensions to R. Because R is open-source, people often write packages to make different functions, features, or analyses possible. 

Your first package will be swirl(). swirl() is a package for learning (and teaching) statistics and R simultaneously and interactively.

Watch [this youtube video](https://youtu.be/-XyrGwp3JRA) to install your first package and start learning R with the swirl() package. 

Complete chapter 1 and 2 in swirl() only.

### R Studio Projects Workflow

Watch R-Studio tutorial: [Projects and R Studio](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-managing-change-part-1/)

### Making Plots

Start making some awesome graphs by working through [section 3.1 to 3.4 in Hadley Wickham's R for Data Science Book](http://r4ds.had.co.nz/data-visualisation.html)

## Version Control with Git and GitHUB

The reason this book is hosted on GitHUB is that we'll be working with GitHUB throughout this guide and throughout your own analysis development. Git is integral for tracking the evolution of a set of files. Basically GitHUB and R is analagous to 'track changes' and Microsoft Word. 

If you're interested in learning why version control is important, I encourage you to skim [Chapter 1; 'Why Git? Why GitHUB' from Jenny Bryans Book](http://happygitwithr.com/big-picture.html#why-git). I reccomend referring back to this book whenever you have a question about using git and GitHUB with R-Studio.

### Setup a GitHUB Account
First, you're going to want to [sign up for a GitHUB account](https://github.com)


### 'Issues' 
(Need to make this repo public for this to be possible)

Now that you have a GitHUB account, you should introduce yourself and let me know you're going to work through this material. To do that go to the issues tab in this repository (repo) and 'create a new issue' and type a message to introduce yourself. Using issues is also a great way to ask questions about course material.

### Fork This Repo
Next, you should fork this repo so that you can access this document from your GitHUB profile, edit it, and make a 'pull request' to suggest edits to me. This serves two purposes: 1) the quality of this guide will be improved if you take time to edit chapters and contribute your insights on what didn't work for you; and 2) forking repos and making pull-requests is training you for the workflow you will use when contributing to colleagues' analyses in the very near future. 

To successfully fork this repo and suggest edits simply go to [my repo here](https://github.com/Br-Johnson/Hakai-Data-Analyst) and click on the name of this chapter: 'new_analysts.Rmd', once it's open click on the pencil icon to suggest edits. Editing automcatically forks the repo and makes a copy in your own list of repos. Now you can make all the edits you'd like and when your happy you can click on 'pull request' to send the updates back to me so I can review them and decide if I should accept your edits and merge them.

If you  aren't successfull forking my repo, read [Chapter 24 of Jenny Brians Book; 'Fork a Repo'](http://happygitwithr.com/fork.html).

### Markdown Syntax
You'll notice that this file is a '.Rmd' file which stands for R  Markdown. [Read this](https://guides.github.com/features/mastering-markdown/) if you're interested in markdown syntax, otherwise come back to it later.

Also, try this [tutorial](http://commonmark.org/help/tutorial/) on how to write using markdown

## Install and set-up Git
Next you're going to install Git. Git tracks the changes you make in R-Studio locally and upon your request, pushes changes to your remote repository at GitHUB. Similar to the relationship between R and R-Studio, Git is the *local* version control system running in the back ground on your computer while GitHUB is the *remote* user interface for saving, tracking, and sharing updated versions of your analyses that is hosted on a remote server. 

Installing Git locally and getting Git to communicate to your remote GitHUB website account, and then getting them to talk with RStudio takes a number of steps to complete...This next part can be painful to work through, but it is 100 % neccesary and well worth it in the long-run.

Install Git and GitHUB and get them talking to R-Studio using [Jenny Bryan's Guide](http://happygitwithr.com/install-git.html), start at chapter 7 and work to the end of chapter 13.

Congratulations you now have setup the three main tools in the R Analyst toolbox: R, R Studio and GitHUB and learned the basics of each component. 

Now to put this all in context, and learn how to use Git, GitHUB and R-Studio I reccomend watching the [R-Studio Essentials tutorial; GitHUB and R-Studio](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-managing-part-2/).

Now you've seen almost all the components of a good workflow, in the next chapter you can put all these things together and work through an example of a Data Analysis using a presecribed, modern approach.

