# Intro to R

In this section you will learn the basics of data wrangling in R. Data wrangling is
the process of importing, tidying, and transforming your data into a format that you 
can visualize and model it. [Tidy data]("http://vita.had.co.nz/papers/tidy-data.pdf") 
is a consistent data format that, when followed closely, dramatically reduces the 
mundane data formatting that is necessary otherwise. The basic concept is that every row is one observation and
every column is a variable. For how simple it sounds, creating tidy data sets
takes some time to get the hang of initially, but is essential for data wrangling in the
tidyverse — the modern set of tools and packages developed in R around the concept of tidy data.

## Data Transformation

The most important set of tools for data wrangling that you will use constantly are
from the package dplyr. They allow you to solve the most of the data manipulation problems you 
will encounter. Those who are able to efficiently get their data into a format
they can visualize and model, will explore and therefore learn the most about their data.
I'd recommend learning these six data wrangling functions off-by-heart:

1) `filter()` to pick observations (rows) based on their values
2) `select()` to pick variables (columns) based on the names
3) `arrange()` to reorder the rows of your data set
4) `mutate()` to create new variables (columns) as a function of existing variables
5) `summarize()` to collapse many values down to a summary
6) `group_by()` to summarize based on the various groups of a variable

To learn how to put this in to practice I recommend reading through [this]("http://r4ds.had.co.nz/transform.html") chapter called 
Data Transformation in R for Data Science and working through all the exercises. This will be a bit of a learning curve but it's time to dive in.

Starting at the [Data Transformation chapter]("http://r4ds.had.co.nz/transform.html") assumes you have some very basic knowledge of R already. 
If that's not the case then I recommend starting at the [Workflow: Basics]("http://r4ds.had.co.nz/workflow-basics.html") chapter.

## Tidying Your Data

Tidy data is best explained by a quote from [Hadley Wickham's paper](http://www.jstatsoft.org/v59/i10/paper) in the Journal of Statistical Software: "Tidy data sets are easy to manipulate, model and visualize, and have a specific structure: each variable is a column, each observation is a row, and each type of observational unit is a table." The 'tidy-verse' model of working in R that I have previously referred to relies on this system of data preparation.

The basic tenets that make a data set tidy are:

1. Each variable must have its own column
2. Each observation must have its own row
3. Each value must have its own cell

Beyond that each type of observational unit should be its own table. That is to say, I wouldn't mix weather metadata from field collection of a fish sample in the same table as the results of a laboratory analysis. Instead I would keep these two types of information, in different tables, but provide a common column in each that allows the tables to be later joined. This is relational data joining that you can read about in the chapter on [Relational Data]("http://r4ds.had.co.nz/relational-data.html") in R for Data Science. If you are involved in producing the data set, I recommend setting up your data collection to follow the tidy data format, to make your life, or the life of your analysts, much easier!

Allow the data stored in Hakai's database is designed to be tidy, sometimes you receive data that is not in a tidy format. The most common problem I run into is that not every row is one observation, it is often many more than one.
To get your data into a tidy format you have to spread out the observations into different rows and create new variables that were once simply listed in rows. Luckily, the package `tidyr` has several functions that make this possible. 

To get a really strong handle on what tidy data is, and to start practising getting data in to a tidy format I recommend working through [this]("http://r4ds.had.co.nz/tidy-data.html") chapter on tidying data in the R for Data Science book. 

## Visualizing Data

In the last chapter you had a teaser of what is possible in terms of making some nice 
looking plots when you worked through the first few sections in the Data Visualization chapter in R for Data Science.
To see what else is possible and to learn the principles of the layered grammar of graphics, I recommend you work through the remaining sections in the Data Visualization Chapter picking up where you left of at the [section on facets]("http://r4ds.had.co.nz/data-visualisation.html#facets")

By the end of this you should have a really solid foundation from which to begin wrangling and visualizing your own data. In the next chapter I'll provide some gerenal principles for developing analyses and a step-by-step guide to follow a modern workflow.

 

