--- 
title: "Hakai Institute R Data-Analyst Guide"
author: "Brett Johnson"
date: "Latest update: `r Sys.Date()`"
cover-image: "~/Google Drive/SEMSP/SEMSP Presentations and Posters/Materials for
Future Presentations/Collaborator Logo_Images/Hakai/Hakai Institute Logo on Red.png"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: HakaiInstitute/hakai_guide_to_r
description: "A guideline for developing analyses in R; getting started, and best-practices"
---
---
```{r serve the book}
#Once you build this book, you can serve the book to auto update in the viewer window by removing the hashtag in the code line below

#bookdown::serve_book(dir = ".", output_dir = "_book", preview = TRUE, in_session = TRUE)

```


# Preface {-}

This is the Hakai Institute's Data Analyst Guide. One of Hakai's core themes that cross-cuts every research axis is 'Big-Data and Modelling'. Our ability to gain insight from our long-term ecological data sets is limited only by our capacity to integrate, and digest data. To that end, this guide was developed to serve as a foundation from which to build the internal technical capacity — using a coherent and systematic approach — to turn data into insight, understanding, and ultimately knowledge about the ecosystems we study.

This book will teach you how to develop analyses in the R programming language. You'll learn project workflow and organization, literate programming style, reproducible research techniques, and collaborative analysis development in an open-science context. 

The Hakai Institute is a research organization based on the coast of
British Columbia, Canada. See the [Hakai Institute Website](http://www.hakai.org) for more information.
